import { Todo } from "./todo";

export const TODOS: Todo[] = [
    {
        id: 1,
        title: "Pate",
        content: "Content Todo 1",
        author: "Nolan",
        isCompleted: true,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 2,
        title: "Jambon",
        content: "Content Todo 2",
        author: "Nolan",
        isCompleted: true,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 3,
        title: "Moutarde",
        content: "Content Todo 2",
        author: "Nolan",
        isCompleted: false,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 4,
        title: "Raclette",
        content: "Content Todo 2",
        author: "Nolan",
        isCompleted: false,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 5,
        title: "Soupe",
        content: "Content Todo 2",
        author: "Nolan",
        isCompleted: false,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 6,
        title: "Ananas",
        content: "Content Todo 2",
        author: "Nolan",
        isCompleted: false,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 7,
        title: "Raclette",
        content: "Content Todo 2",
        author: "Nolan",
        isCompleted: false,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 8,
        title: "Vin",
        content: "Content Todo 2",
        author: "Nolan",
        isCompleted: false,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 9,
        title: "Jaeger",
        content: "Content Todo 2",
        author: "Nolan",
        isCompleted: false,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 10,
        title: "Filet de poulet",
        content: "Content Todo 2",
        author: "Nolan",
        isCompleted: false,
        createdAt: new Date(),
        completedAt: null,
    },
];